;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        indent-for-tab-command
        markdown-cycle
        markdown-exdent-or-delete
        org-self-insert-command
        smex
        whole-line-or-region-kill-region
        whole-line-or-region-yank
        ))

(setq mc/cmds-to-run-once
      '(
        js2-mode-show-node
        whole-line-or-region-kill-ring-save
        ))
